# ~/clientity/src/clientity/core/protocols/interface.py
from __future__ import annotations
import typing as t

from clientity.core.hints import ResponseObject

@t.runtime_checkable
class SyncInterface(t.Protocol):
    def get(self, *args, **kwargs) -> ResponseObject: ...
    def put(self, *args, **kwargs) -> ResponseObject: ...
    def head(self, *args, **kwargs) -> ResponseObject: ...
    def post(self, *args, **kwargs) -> ResponseObject: ...
    def patch(self, *args, **kwargs) -> ResponseObject: ...
    def delete(self, *args, **kwargs) -> ResponseObject: ...
    def options(self, *args, **kwargs) -> ResponseObject: ...
    def request(self, *args, **kwargs) -> ResponseObject: ... # need to see if 'self' is appropriate here as well

@t.runtime_checkable
class AsyncInterface(t.Protocol):
    async def get(self, *args, **kwargs) -> ResponseObject: ...
    async def put(self, *args, **kwargs) -> ResponseObject: ...
    async def head(self, *args, **kwargs) -> ResponseObject: ...
    async def post(self, *args, **kwargs) -> ResponseObject: ...
    async def patch(self, *args, **kwargs) -> ResponseObject: ...
    async def delete(self, *args, **kwargs) -> ResponseObject: ...
    async def options(self, *args, **kwargs) -> ResponseObject: ...
    async def request(self, *args, **kwargs) -> ResponseObject: ... # need to see if 'self' is appropriate here as well



Interface = t.Union[
    SyncInterface,
    AsyncInterface
]

Interfaceable = t.Union[
    t.Callable[[], Interface],
    t.Callable[[], t.Awaitable[Interface]]
]

Interfacing = t.Union[
    Interface,
    Interfaceable
]
